sudo pamac install acpi
sudo pamac install acpid
sudo pamac install amd-ucode
sudo pamac install apparmor
sudo pamac install appimagelauncher
sudo pamac install aptos-bin
sudo pamac install autotiling
sudo pamac install avahi
sudo pamac install b43-fwcutter
sudo pamac install balena-etcher-bin
sudo pamac install base
sudo pamac install base-devel
sudo pamac install bluez
sudo pamac install bluez-utils
sudo pamac install brave-browser
sudo pamac install btchip-udev
sudo pamac install btrfs-progs
sudo pamac install bzip2
sudo pamac install catppuccin-gtk-theme-latte
sudo pamac install catppuccin-gtk-theme-macchiato
sudo pamac install celluloid
sudo pamac install claude-desktop-bin
sudo pamac install cliphist
sudo pamac install cmake
sudo pamac install coreutils
sudo pamac install cpupower
sudo pamac install cronie
sudo pamac install cryptsetup
sudo pamac install dbeaver
sudo pamac install device-mapper
sudo pamac install dex
sudo pamac install dhclient
sudo pamac install diffutils
sudo pamac install discord
sudo pamac install dmraid
sudo pamac install dnsmasq
sudo pamac install dosfstools
sudo pamac install dotnet-sdk
sudo pamac install dropbox
sudo pamac install dropbox-cli
sudo pamac install e2fsprogs
sudo pamac install ecryptfs-utils
sudo pamac install efibootmgr
sudo pamac install elfutils
sudo pamac install elixir
sudo pamac install erlang
sudo pamac install ethtool
sudo pamac install exfatprogs
sudo pamac install f2fs-tools
sudo pamac install ffmpeg
sudo pamac install ffmpegthumbnailer
sudo pamac install file-roller
sudo pamac install firefox
sudo pamac install flashfocus
sudo pamac install font-manager
sudo pamac install fontforge
sudo pamac install gimp
sudo pamac install git-crypt
sudo pamac install glibc-locales
sudo pamac install gnome-epub-thumbnailer
sudo pamac install gnome-font-viewer
sudo pamac install gnome-keyring
sudo pamac install gparted
sudo pamac install greetd
sudo pamac install greetd-tuigreet
sudo pamac install grub
sudo pamac install grub-btrfs
sudo pamac install gtk3-nocsd
sudo pamac install gvfs
sudo pamac install gvfs-mtp
sudo pamac install helix
sudo pamac install imv
sudo pamac install inetutils
sudo pamac install intel-ucode
sudo pamac install iwd
sudo pamac install jdk
sudo pamac install jfsutils
sudo pamac install jq
sudo pamac install julia
sudo pamac install kate
sudo pamac install keybase-bin
sudo pamac install kotlin
sudo pamac install kvantum
sudo pamac install kvantum-theme-catppuccin-git
sudo pamac install laptop-mode-tools
sudo pamac install ledger-live-bin
sudo pamac install ledger-udev
sudo pamac install leiningen-with-completion
sudo pamac install less
sudo pamac install libreoffice-still
sudo pamac install linux612
sudo pamac install linux612-virtualbox-host-modules
sudo pamac install linux66
sudo pamac install lmstudio
sudo pamac install logrotate
sudo pamac install lvm2
sudo pamac install man-db
sudo pamac install man-pages
sudo pamac install manjaro-aur-support
sudo pamac install manjaro-browser-settings
sudo pamac install manjaro-pipewire
sudo pamac install manjaro-release
sudo pamac install manjaro-settings-manager
sudo pamac install manjaro-settings-manager-notifier
sudo pamac install manjaro-sway-settings
sudo pamac install manjaro-system
sudo pamac install manjaro-zsh-config
sudo pamac install mdadm
sudo pamac install memtest86+
sudo pamac install memtest86+-efi
sudo pamac install mhwd
sudo pamac install mhwd-db
sudo pamac install mkinitcpio-openswap
sudo pamac install nano
sudo pamac install nano-syntax-highlighting
sudo pamac install nemo
sudo pamac install nemo-dropbox
sudo pamac install neomutt
sudo pamac install nerdfonts-installer-bin
sudo pamac install network-manager-applet
sudo pamac install networkmanager
sudo pamac install nfs-utils
sudo pamac install nordvpn-bin
sudo pamac install notion-app-electron
sudo pamac install npm
sudo pamac install nss-mdns
sudo pamac install ntfs-3g
sudo pamac install nvm
sudo pamac install obsidian
sudo pamac install ocaml
sudo pamac install oh-my-zsh
sudo pamac install opam
sudo pamac install open-webui-git
sudo pamac install os-prober
sudo pamac install pacman-log-orphans-hook
sudo pamac install pacseek
sudo pamac install pamac-gtk
sudo pamac install pcmanfm-gtk3
sudo pamac install perl
sudo pamac install playerctl
sudo pamac install podman
sudo pamac install podman-compose
sudo pamac install podman-desktop-bin
sudo pamac install podman-tui-git
sudo pamac install polkit-gnome
sudo pamac install postman-bin
sudo pamac install poweralertd
sudo pamac install pulsemixer
sudo pamac install python-pyqt5
sudo pamac install qt5-wayland
sudo pamac install qt5ct
sudo pamac install qt6-wayland
sudo pamac install qt6ct
sudo pamac install reiserfsprogs
sudo pamac install remix-desktop
sudo pamac install rsync
sudo pamac install s-nail
sudo pamac install slack-desktop-wayland
sudo pamac install snapd
sudo pamac install sof-firmware
sudo pamac install steam
sudo pamac install sudo
sudo pamac install sway-services
sudo pamac install swaycwd
sudo pamac install swaylock-effects
sudo pamac install sworkstyle
sudo pamac install syncthing
sudo pamac install sysfsutils
sudo pamac install systemd
sudo pamac install telegram-desktop
sudo pamac install termius
sudo pamac install texinfo
sudo pamac install thunderbird
sudo pamac install timeshift-autosnap-manjaro
sudo pamac install tradingview
sudo pamac install ttf-firacode
sudo pamac install ttf-firacode-nerd
sudo pamac install update-grub
sudo pamac install usbutils
sudo pamac install veracrypt
sudo pamac install vi
sudo pamac install virtualbox
sudo pamac install vlc
sudo pamac install wdisplays
sudo pamac install wget
sudo pamac install which
sudo pamac install wireless-regdb
sudo pamac install wl-clipboard
sudo pamac install wlsunset
sudo pamac install wluma
sudo pamac install wpa_supplicant
sudo pamac install wqy-microhei
sudo pamac install xdg-desktop-portal-wlr
sudo pamac install xdg-user-dirs
sudo pamac install xfsprogs
sudo pamac install xorg-xwayland
sudo pamac install yarn
sudo pamac install yay
sudo pamac install zathura
sudo pamac install zathura-pdf-poppler
sudo pamac install zig
sudo pamac install zlib-ng
sudo pamac install zoom
