#! /usr/bin/env bash
set +x

SERVER=$1
MARKER="###############"


if [ -z "$SERVER" ]
then
      echo "No server name entered"
      echo "======================================================================"
      echo "sh apply <servername> <build-type>"
      echo "=> where:"
      echo "=> servername = server / machine alias"
      echo "=> build-type = home or system"
      exit 1;
fi


if [ -z "$2" ]
then
  BUILD="all"
else
  BUILD=$2
fi

echo "$MARKER"
echo "Building the following configuration:"
echo $SERVER
echo $BUILD

echo "$MARKER"

copy_home_files() {
 # Copy Pictures
 mkdir -p "$HOME/Pictures"
 cp home/noahisla.png "$HOME/Pictures/"

}


apply_home() {
  nix build .#homeConfigurations.${SERVER}.activationPackage
  result/activate
}


apply_system() {
  nix build .#nixosConfigurations.${SERVER}.config.system.build.toplevel
  sudo nixos-rebuild switch --flake
}

apply_all(){
 apply_system
 apply_home
}


case $BUILD in
  "home")
    apply_home;;
  "system")
    apply_system;;
  "all")
    apply_all;;
esac


exit 0
