#! /usr/bin/env bash
set +x

SERVER=$1
USER=$2

if [ -z "$SERVER" ]
then
      echo "No server name entered"
      usage
      exit 1;
fi

if [ -z "$USER" ]
then
      echo "No user name entered"
      usage
      exit 1;
fi

if [ -z "$2" ]
then
  BUILD="all"
else
  BUILD=$2
fi

usage(){

      echo "======================================================================"
      echo "./build <servername> <user> <build-type>"
      echo "=> where:"
      echo "=> servername = server / machine alias"
      echo "=> user = user name"
      echo "=> build-type = home or system"
}

build_home(){
  nix build ".#homeConfigurations.${USER}.activationPackage"
}

build_system(){
 nix build ".#nixosConfigurations.${SERVER}.config.system.build.toplevel"
}

build_all(){
  build_system
  build_home
}

case $BUILD in
  "home")
    build_home;;
  "system")
    build_system;;
  "all")
    build_all;;
esac

exit 0
