-- Replays the classic Hyprland keybindings inside the omarchy session.
--
-- ~/.config/omarchy-cfg/classic-binds.lua is generated by
-- shared/wm/omarchy/default.nix from shared/wm/hyprland/binds.nix, so the
-- classic profile stays the single source of truth. Exec targets whose
-- classic implementation has an omarchy-native equivalent are redirected
-- to that equivalent on the same key (approved 2026-08-31); everything
-- else replays verbatim. The translation core is shared with
-- shared/wm/caelestia/keybinds.lua, which is the tested reference.

local classic = require("omarchy-cfg.classic-binds")

local direction = { l = "left", r = "right", u = "up", d = "down" }

-- binds.nix addresses hjkl by keycode for swapwindow; bind the keysyms
-- instead (layout is gb, so the codes resolve to these letters anyway).
local keycode = { ["43"] = "h", ["44"] = "j", ["45"] = "k", ["46"] = "l" }

local function trim(s)
    return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- Split "MODS,key,dispatcher,args" into at most four fields; exec commands
-- keep any inner whitespace.
local function split_bind(line)
    local parts = {}
    local rest = line
    for _ = 1, 3 do
        local head, tail = rest:match("^([^,]*),(.*)$")
        if not head then break end
        parts[#parts + 1] = trim(head)
        rest = tail
    end
    parts[#parts + 1] = trim(rest)
    return parts
end

local function to_key(mods, key)
    key = keycode[key] or key
    local combo = {}
    for mod in mods:gmatch("%S+") do
        combo[#combo + 1] = mod
    end
    combo[#combo + 1] = key
    return table.concat(combo, " + ")
end

-- Classic exec targets with an omarchy-native equivalent. Keys are the
-- exact exec strings binds.nix produces.
local exec_overrides = {
    -- The classic rofi homage becomes the real quickshell menu.
    ["omarchy-menu"] = function() return hl.dsp.exec_cmd("omarchy-menu toggle") end,
    ["rofi-launcher"] = function() return hl.dsp.exec_cmd("omarchy-menu toggle apps") end,
    ["list-keybinds"] = function() return hl.dsp.exec_cmd("omarchy-menu-keybindings") end,
    ["wlogout --css ~/.config/wlogout/main.css"] = function() return hl.dsp.exec_cmd("omarchy-menu toggle system") end,
    -- The shell owns the lock screen; hyprlock is not configured here.
    ["hyprlock"] = function() return hl.dsp.exec_cmd("omarchy-system-lock") end,
    -- swaync does not run here; the shell owns notifications.
    ["swaync-client -rs"] = function() return hl.dsp.exec_cmd("omarchy-shell notifications showHistory") end,
    ["wallsetter"] = function() return hl.dsp.exec_cmd("omarchy-menu toggle background") end,
    ["emopicker9000"] = function() return hl.dsp.exec_cmd("omarchy-menu-emoji") end,
    ["screenshootin"] = function() return hl.dsp.exec_cmd("omarchy-capture-screenshot") end,
    ["gpu-screen-recorder-gtk"] = function() return hl.dsp.exec_cmd("omarchy-capture-screenrecording") end,
    ["cliphist list | rofi -dmenu | cliphist decode | wl-copy"] = function() return hl.dsp.exec_cmd("omarchy-menu-clipboard") end,
    -- pyprland is not started in this session; the special workspace
    -- stands in for the dropdown terminal, as the caelestia port does.
    ["pypr toggle term"] = function() return hl.dsp.workspace.toggle_special() end,
}

local function to_action(dispatcher, arg)
    if dispatcher == "exec" then
        local override = exec_overrides[arg]
        if override then return override() end
        return hl.dsp.exec_cmd(arg)
    elseif dispatcher == "killactive" then
        return hl.dsp.window.close()
    elseif dispatcher == "pseudo" then
        return hl.dsp.window.pseudo()
    elseif dispatcher == "layoutmsg" then
        return hl.dsp.layout(arg)
    elseif dispatcher == "fullscreen" then
        return hl.dsp.window.fullscreen({ mode = "fullscreen" })
    elseif dispatcher == "togglefloating" then
        return hl.dsp.window.float()
    elseif dispatcher == "workspaceopt" then
        -- No Lua dispatcher for workspaceopt; go through hyprctl.
        return hl.dsp.exec_cmd("hyprctl dispatch workspaceopt " .. arg)
    elseif dispatcher == "exit" then
        return hl.dsp.exit()
    elseif dispatcher == "movewindow" then
        return hl.dsp.window.move({ direction = direction[arg] })
    elseif dispatcher == "swapwindow" then
        return hl.dsp.window.swap({ direction = direction[arg] })
    elseif dispatcher == "movefocus" then
        return hl.dsp.focus({ direction = direction[arg] })
    elseif dispatcher == "workspace" then
        return hl.dsp.focus({ workspace = tonumber(arg) or arg })
    elseif dispatcher == "movetoworkspace" then
        return hl.dsp.window.move({ workspace = tonumber(arg) or arg })
    elseif dispatcher == "togglespecialworkspace" then
        return hl.dsp.workspace.toggle_special()
    elseif dispatcher == "cyclenext" then
        return hl.dsp.window.cycle_next()
    elseif dispatcher == "bringactivetotop" then
        return hl.dsp.window.bring_to_top()
    end
    print("classic-binds: unhandled dispatcher '" .. dispatcher .. "'")
end

-- A key bound to several dispatchers in binds.nix (ALT+Tab) fires them all.
local order, actions = {}, {}
for _, line in ipairs(classic.bind) do
    local parts = split_bind(line)
    local action = to_action(parts[3], parts[4] or "")
    if action then
        local key = to_key(parts[1], parts[2])
        if not actions[key] then
            actions[key] = {}
            order[#order + 1] = key
        end
        table.insert(actions[key], action)
    end
end

for _, key in ipairs(order) do
    local list = actions[key]
    if #list == 1 then
        hl.bind(key, list[1])
    else
        hl.bind(key, function()
            for _, action in ipairs(list) do
                if type(action) == "function" then action() else hl.dispatch(action) end
            end
        end)
    end
end

local mouse_dispatchers = {
    movewindow   = function() return hl.dsp.window.drag() end,
    resizewindow = function() return hl.dsp.window.resize() end,
}
for _, line in ipairs(classic.bindm) do
    local parts = split_bind(line)
    local dispatcher = mouse_dispatchers[parts[3]]
    if dispatcher then
        hl.bind(to_key(parts[1], parts[2]), dispatcher(), { mouse = true })
    else
        print("classic-binds: unhandled mouse dispatcher '" .. tostring(parts[3]) .. "'")
    end
end
