# Nix guideline compliant 2026-09-01
{
  pkgs,
  lib,
  username,
  ...
}:
let
  inherit (import ../../../homes/${username}/variables.nix)
    keyboardLayout
    extraMonitorSettings
    ;

  omarchy = pkgs.omarchy-nixified;

  classicCatalog = import ../hyprland/keybind-catalog.nix { inherit username; };
  catalogToLua = import ../hyprland/catalog-to-lua.nix { inherit lib; };

  # hyprlang "monitor=output,mode,position,scale" lines from variables.nix
  # translated to hl.monitor calls (same translation as the caelestia
  # module).
  monitorLines = builtins.filter (line: lib.hasPrefix "monitor=" line) (
    lib.splitString "\n" extraMonitorSettings
  );
  toLuaMonitor =
    line:
    let
      parts = lib.splitString "," (lib.removePrefix "monitor=" line);
    in
    lib.optionalString (builtins.length parts >= 4) ''
      hl.monitor({
          output   = "${builtins.elemAt parts 0}",
          mode     = "${builtins.elemAt parts 1}",
          position = "${builtins.elemAt parts 2}",
          scale    = ${builtins.elemAt parts 3},
      })
    '';
in
{
  # Applications the omarchy desktop surface reaches for. Upstream expects
  # them from Arch packages, which the session cannot install; the two that
  # the shipped desktop depends on come first, then the optional set whose
  # menu rows would otherwise be permanently unusable. Anything not listed
  # here still shows an Install row, which now fails with a message naming
  # the flake rather than silently doing nothing.
  home.packages = with pkgs; [
    # omarchy-launch-nautilus and its default keybind in
    # default/hypr/bindings/applications.lua; also the target of
    # omarchy-theme-bg-install.
    nautilus
    # The menu's Trigger -> Share section (omarchy-menu-share) and the
    # window rules in default/hypr/apps/localsend.lua.
    localsend
    # Offered by the menu's Install section and covered by upstream's
    # window rules; without them those rows can never succeed.
    kdePackages.kdenlive
    pinta
    xournalpp
    zed-editor
    retroarch
  ];

  xdg.configFile = {
    # Session entry point; the greeter wrapper passes
    # --config ~/.config/hypr/omarchy.lua and exports OMARCHY_PATH.
    "hypr/omarchy.lua".text = ''
      -- Generated by shared/wm/omarchy/default.nix. Follows upstream's
      -- config/hypr/hyprland.lua template, with classic keybindings
      -- replacing the omarchy defaults.
      dofile((os.getenv("OMARCHY_PATH") or "${omarchy}") .. "/default/hypr/bootstrap.lua")

      omarchy_default_bindings = false

      require("default.hypr.omarchy")

      require("omarchy-cfg.monitors")
      require("omarchy-cfg.input")
      require("omarchy-cfg.bindings")

      -- Toggle config flags dynamically, as upstream's template does.
      require("default.hypr.toggles")
    '';

    "omarchy-cfg/monitors.lua".text = ''
      ${lib.concatStrings (map toLuaMonitor monitorLines)}
    '';

    "omarchy-cfg/input.lua".text = ''
      -- default/hypr/input.lua reads the layout from vconsole and falls
      -- back to "us"; override with the configured layout.
      hl.config({
          input = {
              kb_layout = "${keyboardLayout}",
          },
      })
    '';

    "omarchy-cfg/bindings.lua".source = ./bindings.lua;

    "omarchy-cfg/classic-binds.lua".text = catalogToLua classicCatalog;
  };

  # default/hypr resolves omarchy.current.theme.* from
  # ~/.local/state/omarchy; seed the default theme so the first omarchy
  # login is themed. omarchy-theme-set owns the links afterwards.
  home.activation.omarchySeedTheme = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    state="$HOME/.local/state/omarchy/current"
    if [ ! -e "$state/theme" ]; then
      mkdir -p "$state"
      ln -sfn "${omarchy}/themes/tokyo-night" "$state/theme"
      ln -sfn "${omarchy}/themes/tokyo-night/backgrounds/0-winding-road.webp" \
        "$state/background"
    fi
  '';

  # Writable plugin/theme/hook directories omarchy expects to own.
  home.activation.omarchyConfigDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "$HOME/.config/omarchy/themes" \
             "$HOME/.config/omarchy/plugins" \
             "$HOME/.config/omarchy/hooks"
  '';
}
