# Nix guideline compliant 2026-09-01
{
  pkgs,
  lib,
  username,
  ...
}:
let
  inherit (import ../../../homes/${username}/variables.nix)
    keyboardLayout
    extraMonitorSettings
    ;

  # Omnixy takes the vendored Omarchy 4 tree as its base; features from the
  # classic and caelestia profiles are adopted one by one on top of it. The
  # decision record lives in agents/ alongside the scaffold notes.
  omarchy = pkgs.omarchy-nixified;

  classicCatalog = import ../hyprland/keybind-catalog.nix { inherit username; };
  catalogToLua = import ../hyprland/catalog-to-lua.nix { inherit lib; };

  # hyprlang "monitor=output,mode,position,scale" lines from variables.nix
  # translated to hl.monitor calls (same translation as the omarchy module).
  monitorLines = builtins.filter (line: lib.hasPrefix "monitor=" line) (
    lib.splitString "\n" extraMonitorSettings
  );
  toLuaMonitor =
    line:
    let
      parts = lib.splitString "," (lib.removePrefix "monitor=" line);
    in
    lib.optionalString (builtins.length parts >= 4) ''
      hl.monitor({
          output   = "${builtins.elemAt parts 0}",
          mode     = "${builtins.elemAt parts 1}",
          position = "${builtins.elemAt parts 2}",
          scale    = ${builtins.elemAt parts 3},
      })
    '';

  # Classic's wallsetter, reshaped for the shell-owned background (decision
  # record: agents/2026-09-01-001, backlog item 7). The shell draws the
  # background itself from the current/background symlink, so rotation is a
  # timer retargeting that symlink through omarchy-theme-bg-set — running
  # wallsetter's awww daemon here would fight the shell's own layer.
  rotateBackground = pkgs.writeShellScript "omnixy-background-rotate" ''
    set -euo pipefail
    dir="$HOME/Pictures/Wallpapers"
    [ -d "$dir" ] || exit 0
    current=$(readlink "$HOME/.local/state/omarchy/current/background" 2>/dev/null || true)
    img=$(find -L "$dir" -maxdepth 1 -type f \
      \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.gif' -o -iname '*.bmp' -o -iname '*.webp' \) \
      | grep -vFx "$current" | shuf -n 1 || true)
    # Plain && would fail the unit under set -e when the only image is
    # already current and the pick comes back empty.
    if [ -n "$img" ]; then
      omarchy-theme-bg-set "$img"
    fi
  '';

  # Bar modules replacing the two waybar widgets the Omarchy bar lacks
  # (decision record: agents/2026-09-01-001, backlog item 1). systemstats
  # reuses waybar's exec line through the bar's custom command module;
  # pushover is the custom qml module above. Seeded into shell.json rather
  # than HM-managed so bar gestures and `omarchy bar` keep working.
  barAdditions = {
    center = [
      {
        id = "custom.systemstats";
        exec = ''echo "󰍛 $(free | awk '/Mem:/ {printf "%.0f%%", ($3/$2)*100}') | 󰻠 $(cat /proc/pressure/cpu | awk '/^some/ {print $2}' | cut -d= -f2) | 󰋊 $(df -h / | awk 'NR==2 {print $5}')"'';
        interval = 5;
        tooltip = "Memory used | CPU pressure | root disk used";
        onClick = "omarchy-launch-floating-terminal-with-presentation btop";
      }
    ];
    right = [
      {
        id = "custom.pushover";
        source = "~/.config/omarchy/bar/modules/Pushover.qml";
      }
    ];
  };
in
{
  # Theme state seeding and the writable ~/.config/omarchy directories come
  # from the omarchy module, which is always imported alongside this one;
  # both sessions share ~/.local/state/omarchy until omnixy grows its own
  # theming decisions.
  xdg.configFile = {
    # Session entry point; the greeter wrapper passes
    # --config ~/.config/hypr/omnixy.lua and exports OMARCHY_PATH.
    "hypr/omnixy.lua".text = ''
      -- Generated by shared/wm/omnixy/default.nix. Follows upstream's
      -- config/hypr/hyprland.lua template, with classic keybindings
      -- replacing the omarchy defaults.
      dofile((os.getenv("OMARCHY_PATH") or "${omarchy}") .. "/default/hypr/bootstrap.lua")

      omarchy_default_bindings = false

      require("default.hypr.omarchy")

      require("omnixy-cfg.monitors")
      require("omnixy-cfg.input")
      require("omnixy-cfg.bindings")
      require("omnixy-cfg.session")

      -- Toggle config flags dynamically, as upstream's template does.
      require("default.hypr.toggles")
    '';

    "omnixy-cfg/monitors.lua".text = ''
      ${lib.concatStrings (map toLuaMonitor monitorLines)}
    '';

    "omnixy-cfg/input.lua".text = ''
      -- default/hypr/input.lua reads the layout from vconsole and falls
      -- back to "us"; override with the configured layout.
      hl.config({
          input = {
              kb_layout = "${keyboardLayout}",
          },
      })
    '';

    "omnixy-cfg/bindings.lua".source = ./bindings.lua;

    "omnixy-cfg/session.lua".text = ''
      -- The session wrapper starts Hyprland bare, without uwsm, so nothing
      -- raises graphical-session.target and user services gated on it (the
      -- pushover-bridge among them) would never start. graphical-session.target
      -- refuses manual starts, and hyprland-session.target would drag in the
      -- classic stack (waybar, dunst, hypridle) that the shell replaces, so
      -- the session starts its own BindsTo wrapper target instead.
      hl.on("hyprland.start", function()
          hl.exec_cmd("systemctl --user start omnixy-session.target")
      end)
    '';

    "omarchy/bar/modules/Pushover.qml".source = ./Pushover.qml;

    "omnixy-cfg/classic-binds.lua".text = catalogToLua classicCatalog;
  };

  systemd.user = {
    # Startable stand-in for graphical-session.target (which refuses manual
    # starts). Deliberately not hyprland-session.target: that would pull in
    # waybar, dunst and hypridle, whose jobs the quickshell shell owns here.
    targets.omnixy-session.Unit = {
      Description = "Omnixy quickshell session";
      BindsTo = [ "graphical-session.target" ];
      Wants = [ "graphical-session-pre.target" ];
      After = [ "graphical-session-pre.target" ];
    };

    # Wallsetter's cadence (a random wallpaper every two minutes), scoped to
    # the omnixy session by the target. omarchy-theme-bg-set needs the
    # omarchy bin and runtime tools for its omarchy-shell IPC call; the
    # shell's symlink poll covers the case where IPC misses.
    services.omnixy-background-rotate = {
      Unit = {
        Description = "Rotate the Omnixy background from ~/Pictures/Wallpapers";
        PartOf = [ "omnixy-session.target" ];
      };
      Service = {
        Type = "oneshot";
        ExecStart = "${rotateBackground}";
        Environment = [
          "PATH=${omarchy}/bin:${omarchy.runtimePath}:${
            lib.makeBinPath [
              pkgs.bash
              pkgs.coreutils
              pkgs.findutils
              pkgs.gnugrep
            ]
          }"
        ];
      };
    };

    timers.omnixy-background-rotate = {
      Unit = {
        Description = "Timer for the Omnixy background rotation";
        PartOf = [ "omnixy-session.target" ];
      };
      Timer = {
        OnActiveSec = "5s";
        OnUnitActiveSec = "2min";
      };
      Install.WantedBy = [ "omnixy-session.target" ];
    };
  };

  # Seed shell.json with the two extra bar modules the first time only: the
  # shell treats the user file as canonical once it exists (no deep-merge),
  # and bar gestures rewrite it at runtime, so it cannot be a store symlink.
  # An already-customised shell.json is left alone; the modules can then be
  # added with `omarchy bar set` instead.
  home.activation.omnixyBarLayout = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    cfg="$HOME/.config/omarchy/shell.json"
    if [ ! -e "$cfg" ]; then
      mkdir -p "$HOME/.config/omarchy"
      ${pkgs.jq}/bin/jq --argjson add ${lib.escapeShellArg (builtins.toJSON barAdditions)} \
        '.bar.layout.center += $add.center | .bar.layout.right = $add.right + .bar.layout.right' \
        "${omarchy}/config/omarchy/shell.json" >"$cfg"
    fi
  '';
}
