-- Replaces the caelestia dots' keybinds.lua so the caelestia session uses
-- the classic Hyprland keybindings.
--
-- ~/.config/caelestia/classic-binds.lua is generated by
-- shared/wm/caelestia/default.nix from shared/wm/hyprland/binds.nix, so the
-- classic profile stays the single source of truth: edit binds.nix and both
-- sessions pick the change up on the next rebuild. This file translates
-- those hyprlang bind lines into hl API calls, then layers caelestia shell
-- bindings onto keys the classic set leaves free.

local fn      = require("utils.functions")
local classic = require("classic-binds")

local direction = { l = "left", r = "right", u = "up", d = "down" }

-- binds.nix addresses hjkl by keycode for swapwindow; bind the keysyms
-- instead (layout is gb, so the codes resolve to these letters anyway).
local keycode = { ["43"] = "h", ["44"] = "j", ["45"] = "k", ["46"] = "l" }

local function trim(s)
    return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- Split "MODS,key,dispatcher,args" into at most four fields; exec commands
-- keep any inner whitespace.
local function split_bind(line)
    local parts = {}
    local rest = line
    for _ = 1, 3 do
        local head, tail = rest:match("^([^,]*),(.*)$")
        if not head then break end
        parts[#parts + 1] = trim(head)
        rest = tail
    end
    parts[#parts + 1] = trim(rest)
    return parts
end

local function to_key(mods, key)
    key = keycode[key] or key
    local combo = {}
    for mod in mods:gmatch("%S+") do
        combo[#combo + 1] = mod
    end
    combo[#combo + 1] = key
    return table.concat(combo, " + ")
end

-- Classic exec targets whose daemon only runs in the classic session get a
-- shell-native replacement on the same key.
local exec_overrides = {
    -- swaync does not run here; the caelestia shell owns notifications.
    ["swaync-client -rs"] = function() return hl.dsp.global("caelestia:clearNotifs") end,
    -- Use the shell's integrated lock screen instead of bare hyprlock.
    ["hyprlock"] = function() return hl.dsp.global("caelestia:lock") end,
    -- pyprland is not started in this session; the dots' scratchpad
    -- workspace toggle stands in for the dropdown terminal.
    ["pypr toggle term"] = function() return fn.toggle("specialws") end,
    -- wallsetter drives awww-daemon, which is not running here.
    ["wallsetter"] = function() return hl.dsp.exec_cmd("caelestia wallpaper -r") end,
}

local function to_action(dispatcher, arg)
    if dispatcher == "exec" then
        local override = exec_overrides[arg]
        if override then return override() end
        return hl.dsp.exec_cmd(arg)
    elseif dispatcher == "killactive" then
        return hl.dsp.window.close()
    elseif dispatcher == "pseudo" then
        return hl.dsp.window.pseudo()
    elseif dispatcher == "layoutmsg" then
        return hl.dsp.layout(arg)
    elseif dispatcher == "fullscreen" then
        return hl.dsp.window.fullscreen({ mode = "fullscreen" })
    elseif dispatcher == "togglefloating" then
        return hl.dsp.window.float()
    elseif dispatcher == "workspaceopt" then
        -- No Lua dispatcher for workspaceopt; go through hyprctl.
        return hl.dsp.exec_cmd("hyprctl dispatch workspaceopt " .. arg)
    elseif dispatcher == "exit" then
        return hl.dsp.exit()
    elseif dispatcher == "movewindow" then
        return hl.dsp.window.move({ direction = direction[arg] })
    elseif dispatcher == "swapwindow" then
        return hl.dsp.window.swap({ direction = direction[arg] })
    elseif dispatcher == "movefocus" then
        return hl.dsp.focus({ direction = direction[arg] })
    elseif dispatcher == "workspace" then
        return hl.dsp.focus({ workspace = tonumber(arg) or arg })
    elseif dispatcher == "movetoworkspace" then
        return hl.dsp.window.move({ workspace = tonumber(arg) or arg })
    elseif dispatcher == "togglespecialworkspace" then
        return hl.dsp.workspace.toggle_special()
    elseif dispatcher == "cyclenext" then
        return hl.dsp.window.cycle_next()
    elseif dispatcher == "bringactivetotop" then
        return hl.dsp.window.bring_to_top()
    end
    print("classic-binds: unhandled dispatcher '" .. dispatcher .. "'")
end

-- A key bound to several dispatchers in binds.nix (ALT+Tab) fires them all.
local order, actions = {}, {}
for _, line in ipairs(classic.bind) do
    local parts = split_bind(line)
    local action = to_action(parts[3], parts[4] or "")
    if action then
        local key = to_key(parts[1], parts[2])
        if not actions[key] then
            actions[key] = {}
            order[#order + 1] = key
        end
        table.insert(actions[key], action)
    end
end

for _, key in ipairs(order) do
    local list = actions[key]
    if #list == 1 then
        hl.bind(key, list[1])
    else
        hl.bind(key, function()
            for _, action in ipairs(list) do
                if type(action) == "function" then action() else hl.dispatch(action) end
            end
        end)
    end
end

local mouse_dispatchers = {
    movewindow   = function() return hl.dsp.window.drag() end,
    resizewindow = function() return hl.dsp.window.resize() end,
}
for _, line in ipairs(classic.bindm) do
    local parts = split_bind(line)
    local dispatcher = mouse_dispatchers[parts[3]]
    if dispatcher then
        hl.bind(to_key(parts[1], parts[2]), dispatcher(), { mouse = true })
    else
        print("classic-binds: unhandled mouse dispatcher '" .. tostring(parts[3]) .. "'")
    end
end

-- Caelestia shell bindings kept from the dots, restricted to keys the
-- classic set leaves free. Dropped because classic owns the key: SUPER+K
-- (panels), SUPER+L (lock; classic SUPER+SHIFT+L locks instead), SUPER+S,
-- SUPER+D, SUPER+M, SUPER+V and the XF86 media/volume/brightness row.
local locked    = { locked = true }
local release   = { release = true }
local repeating = { repeating = true }

hl.bind("SUPER + SUPER_L", hl.dsp.global("caelestia:launcher"), release)
hl.bind("CTRL + ALT + Delete", hl.dsp.global("caelestia:session"))
hl.bind("SUPER + N", hl.dsp.global("caelestia:sidebar"))
hl.bind("CTRL + ALT + C", hl.dsp.global("caelestia:clearNotifs"), locked)

-- Moved off the dots' SUPER+ALT+L, which classic uses for swapwindow.
hl.bind("CTRL + SUPER + L", function()
    hl.dispatch(hl.dsp.exec_cmd("caelestia shell -d"))
    hl.dispatch(hl.dsp.global("caelestia:lock"))
end)
-- Moved off CTRL+SUPER+(SHIFT|ALT)+R, which classic uses for desktop-reminder.
hl.bind(
    "CTRL + SUPER + ALT + SHIFT + R",
    hl.dsp.exec_cmd("qs -c caelestia kill; sleep .1; caelestia shell -d"),
    release
)

hl.bind("Print", hl.dsp.exec_cmd("caelestia screenshot"), locked)
hl.bind("SUPER + SHIFT + S", hl.dsp.global("caelestia:screenshotFreeze"))
hl.bind("SUPER + SHIFT + ALT + S", hl.dsp.global("caelestia:screenshot"))
hl.bind("SUPER + Period", hl.dsp.exec_cmd("pkill fuzzel || caelestia emoji -p"))

hl.bind("SUPER + Comma", hl.dsp.group.toggle())
hl.bind("SUPER + SHIFT + Comma", hl.dsp.group.lock_active())
hl.bind("SUPER + U", hl.dsp.window.move({ out_of_group = true }))

hl.bind("CTRL + SHIFT + Escape", fn.toggle("sysmon"))

hl.bind("CTRL + SUPER + Space", hl.dsp.global("caelestia:mediaToggle"), locked)
hl.bind("CTRL + SUPER + Equal", hl.dsp.global("caelestia:mediaNext"), locked)
hl.bind("CTRL + SUPER + Minus", hl.dsp.global("caelestia:mediaPrev"), locked)
hl.bind("CTRL + SUPER + Backspace", hl.dsp.global("caelestia:mediaStop"), locked)
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), locked)

hl.bind("SUPER + Minus", fn.resize_active_window(-10, 0), repeating)
hl.bind("SUPER + Equal", fn.resize_active_window(10, 0), repeating)
hl.bind("SUPER + SHIFT + Minus", fn.resize_active_window(0, -10), repeating)
hl.bind("SUPER + SHIFT + Equal", fn.resize_active_window(0, 10), repeating)

hl.bind("CTRL + SUPER + Backslash", hl.dsp.window.center())
hl.bind("CTRL + SUPER + ALT + Backslash", function()
    hl.dispatch(hl.dsp.window.resize(fn.resize_by_screen(55, 70)))
    hl.dispatch(hl.dsp.window.center())
end)
hl.bind("SUPER + ALT + Backslash", function()
    local a = hl.get_active_window()
    if a then
        local pip = fn.move_actions(a) or {}
        if not a.floating then table.insert(pip, 1, hl.dsp.window.float()) end
        table.insert(pip, hl.dsp.window.pin({ action = "on", window = "address:" .. a.address }))

        for _, x in ipairs(pip) do
            hl.dispatch(x)
        end
    end
end)
