name: "Build ISO Image"
on:
  push: {}
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually



jobs:
  build:
    strategy:
      matrix:
        system:
          - redtail
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
          submodules: true
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: ./build ${{ matrix.system }}


