name: "Build ISO Image"
on:
  push: {}
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually



jobs:
  build:
    strategy:
      matrix:
        system:
          - redtail
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.0
      with:
          submodules: true
    - name: set file permissions
      run: chmod +x apply && chmod +x build
    - name: install nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: install cachix
      uses: cachix/cachix-action@v10
      with:
        name: glottologist
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: ./build ${{ matrix.system }}


